### PR TITLE
User from file

### PR DESCRIPTION
**Pull request by mclaughlinconnor**
Since the `File` stuff has been finished,  we can use that in the main menu to avoid hardcoding in drinks, etc now

### CODE REVIEW

**Review by MPanek6 — CHANGES_REQUESTED** [review]
change `if username == self.username` to `if username.lower() == self.username.lower()` so its not case sensitive. Line 38

**Comment by mclaughlinconnor** [comment]
@MPanek6 If we change it to be case-insensitive in the login code, we will be stuck with having it that way forever (users will not know how their username is actually capitalized). I would agree with you here generally, but we should force lower case on user creation (which doesn't exist) and not as part of the authentication so that in the future if we want to change the case-sensitivity of usernames we can.

**Comment by MPanek6** [comment]
a username can still be stored with capitalisation, and be displayed like so, for example 'hello UserName'. I'd say change to .lower()

**Comment by mclaughlinconnor** [comment]
Fair enough, case-insensitive usernames it is then

**Comment by MPanek6** [comment]
merging

**Pull request merged**
